services:
  postgres:
    image: postgres:16
    container_name: airbnb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airbnb_user
      POSTGRES_PASSWORD: airbnb_pass
      POSTGRES_DB: airbnb_manager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
